// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingApp.Model;

namespace ParkingApp.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20200726131544_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingApp.Model.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Model = "Chevrolet Aveo"
                        },
                        new
                        {
                            Id = 2L,
                            Model = "Opel Corsa"
                        },
                        new
                        {
                            Id = 3L,
                            Model = "Renault Clio"
                        });
                });

            modelBuilder.Entity("ParkingApp.Model.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CarId")
                        .HasColumnType("bigint");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CarId = 1L,
                            LicensePlate = "lalalalal"
                        },
                        new
                        {
                            Id = 2L,
                            CarId = 1L,
                            LicensePlate = "nanananna"
                        },
                        new
                        {
                            Id = 3L,
                            CarId = 1L,
                            LicensePlate = "blblblbl"
                        });
                });

            modelBuilder.Entity("ParkingApp.Model.Parked", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<long>("ParkingSpaceId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestStatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parked");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DriverId = 1L,
                            From = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParkingSpaceId = 1L,
                            RequestStatusId = 1L,
                            To = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            DriverId = 1L,
                            From = new DateTime(2020, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParkingSpaceId = 1L,
                            RequestStatusId = 1L,
                            To = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            DriverId = 1L,
                            From = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParkingSpaceId = 1L,
                            RequestStatusId = 1L,
                            To = new DateTime(2019, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ParkingApp.Model.ParkingSpace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<long>("ParkingTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpaces");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Lat = 20.300000000000001,
                            Lng = 13.300000000000001,
                            ParkingTypeId = 1L,
                            RateId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Lat = 40.299999999999997,
                            Lng = 30.300000000000001,
                            ParkingTypeId = 1L,
                            RateId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Lat = -13.300000000000001,
                            Lng = 40.299999999999997,
                            ParkingTypeId = 1L,
                            RateId = 1L
                        });
                });

            modelBuilder.Entity("ParkingApp.Model.ParkingType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Type = "handicapped",
                            Zone = 2
                        },
                        new
                        {
                            Id = 2L,
                            Type = "regular",
                            Zone = 2
                        },
                        new
                        {
                            Id = 3L,
                            Type = "handicapped",
                            Zone = 2
                        });
                });

            modelBuilder.Entity("ParkingApp.Model.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaymentPanelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 3000.5m,
                            IssuedAt = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentPanelId = 2L,
                            Status = "status"
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 1066.1m,
                            IssuedAt = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentPanelId = 2L,
                            Status = "status2"
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 3111.9m,
                            IssuedAt = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentPanelId = 2L,
                            Status = "status3"
                        });
                });

            modelBuilder.Entity("ParkingApp.Model.PaymentPanel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChargingStart")
                        .HasColumnType("datetime2");

                    b.Property<long>("ParkedId")
                        .HasColumnType("bigint");

                    b.Property<int>("PayedForHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentPanels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChargingStart = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParkedId = 1L,
                            PayedForHours = 2
                        },
                        new
                        {
                            Id = 2L,
                            ChargingStart = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParkedId = 1L,
                            PayedForHours = 4
                        },
                        new
                        {
                            Id = 3L,
                            ChargingStart = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParkedId = 1L,
                            PayedForHours = 1
                        });
                });

            modelBuilder.Entity("ParkingApp.Model.Rate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("PriceHourly")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PriceHourly = 6.1m
                        },
                        new
                        {
                            Id = 2L,
                            PriceHourly = 2.1m
                        },
                        new
                        {
                            Id = 3L,
                            PriceHourly = 4.6m
                        });
                });

            modelBuilder.Entity("ParkingApp.Model.RequestStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "neki status"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "drugi status"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "treci status"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
